/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TTSService_CONSTANTS_H
#define TTSService_CONSTANTS_H

#include "TTSService_types.h"

namespace arobot { namespace tts {

class TTSServiceConstants {
 public:
  TTSServiceConstants();

};

extern const TTSServiceConstants g_TTSService_constants;

}} // namespace

#endif
